### ISSUE TITLE
Where is the mapping logic?

### ISSUE THREAD

**Issue by PierreKiwi** [awslabs/aws-appflow-custom-connector-python#1]
Hello @banvipul,

I have read the code of this repo (thanks for sharing!), and I would like to know to see where the mapping logic is.
Let's say I have a task like this

```
{
    "connectorOperator": {
      "S3": "NO_OP"
    },
    "destinationField": "Active__c",
    "sourceFields": ["Active"],
    "taskProperties": [
      {
        "Key": "DESTINATION_DATA_TYPE",
        "Value": "boolean"
      }
    ],
    "taskType": "Map"
  },
  ```

Where is the conversion from `Active` to `Active__c` supposed to happen? Is it something the custom connector must do? If yes, where (maybe RecordHandler)?
Or does it happen somewhere in the `custom_connector_sdk`?

Thanks for your help!

**Comment by freimer** [comment]
Good question, I don't see it in the SDK either.  The following is a complete guess, as I don't have any information on how AppFlow works internally.

That said, a connector can be both a source and a destination, correct?  I'm assuming that AWS has some internal components of the service that hook together a source and a destination, kind of like a SingerIO tap/target.

If your connector supports reading it would handle the retrieve_data method for the RecordHandler.  When the handler is created, there is a selected_field_names in the `__init__`  that is provided.  What is returned, as far as the data, is a list of JSON, one record per list item.

If your connector can write data, then it receives the data as JSON (At least the SalesForce example does a json.loads on the record passed in the write request).

So, AWS must have some middleware that gets the response from the connector reading the data, does the conversion (along with transforms?  I don't see any of that in the SDK either), and passes the renamed fields / transformed data to the connector writing the data.

I don't think the connector is doing the mapping of fields or transforms itself.  But, like I said, this is just a guess.

While it is great to see the SDK, it would be awesome if we could get the actual protocol specs as far as input/output to the Lambda functions.  Maybe it's out there and I'm missing it?

**Comment by freimer** [comment]
Actually, are the JSON files under customer_connector_sdk/test/resources a good example of the "schema" for the Lambda function input/output?

**Comment by banvipul** [comment]
> Hello @banvipul,
> 
> I have read the code of this repo (thanks for sharing!), and I would like to know to see where the mapping logic is. Let's say I have a task like this
> 
> ```
> {
>     "connectorOperator": {
>       "S3": "NO_OP"
>     },
>     "destinationField": "Active__c",
>     "sourceFields": ["Active"],
>     "taskProperties": [
>       {
>         "Key": "DESTINATION_DATA_TYPE",
>         "Value": "boolean"
>       }
>     ],
>     "taskType": "Map"
>   },
> ```
> 
> Where is the conversion from `Active` to `Active__c` supposed to happen? Is it something the custom connector must do? If yes, where (maybe RecordHandler)? Or does it happen somewhere in the `custom_connector_sdk`?
> 
> Thanks for your help!

Hello @PierreKiwi [PierreKiwi](https://github.com/PierreKiwi) Thanks for your interest. This mapping is taken care by AppFlow. Custom Connector does not need to worry about this mapping task.

**Comment by PierreKiwi** [comment]
Hey @freimer and @banvipul,
Thanks for your responses. Happy to read that this mapping is managed for us :).
I will start working on a custom connector very shorthly, so more questions may arise!

**Comment by freimer** [comment]
@PierreKiwi it is nowhere near complete, but I started a SDK for Go here: https://gitlab.com/freimer-go/aws/appflow.  I can say that it works for what is in there so far.  I wrote a simple connector using the Python SDK here, and re-implemented it with the Go SDK and it works just the same, but perhaps a bit quicker ;-)

**Comment by PierreKiwi** [comment]
Nice one @freimer !
I will have a look to your repo for inspiration :)
