### ISSUE TITLE
Custom connector tools deploy script does not require mvn on python 

### ISSUE THREAD

**Issue by armaseg** [awslabs/aws-appflow-custom-connector-python#18]
Deploy.sh on python doesn't require mvn here https://github.com/awslabs/aws-appflow-custom-connector-python/blob/9a7e61d7bdc15fb82dadb2344b74d1178c9695c6/custom_connector_tools/README.md?plain=1#L6

MVN is part of the java Deploy.sh script of https://github.com/awslabs/aws-appflow-custom-connector-java/blob/934f36e2688112f1567d9d0abb45d04899c15592/custom-connector-tools/deploy.sh#L54

**Comment by aaronsven** [comment]
https://github.com/awslabs/aws-appflow-custom-connector-python/pull/19
