### ISSUE TITLE
Git dependency installs without any submodules

### ISSUE THREAD

**Issue by mgwidmann** [awslabs/aws-appflow-custom-connector-python#3]
Given the following `setup.py` file:

```python
from setuptools import setup

setup(
    name="my-app",
    version="0.0.1",
    install_requires=[
        "custom_connector_sdk @ git+https://github.com/awslabs/aws-appflow-custom-connector-python@main",
        "setuptools~=57.0.0",
        "boto3~=1.20.47",
    ]
)
```

The following is produced in my `env/lib/python3.8/site-packages/custom_connector_sdk` folder:

```
$ ls env/lib/python3.8/site-packages/custom_connector_sdk/
__init__.py    __pycache__
```

Leading to the import not working:

```
$ python
Python 3.8.12 (default, Mar  2 2022, 12:24:02)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import custom_connector_sdk
>>> from custom_connector_sdk.connector.fields import WriteOperationType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'custom_connector_sdk.connector'
```

Theres no code in the package, making this project broken when using it as a git based dependency. The only way to use it is as a git submodule or to copy the code into your personal codebase (leading to upgrade issues later).

I think whats missing is the use of `find_packages`, would you accept a PR to fix this?

**Comment by freimer** [comment]
This would be useful.  There's also package_data needed for the query filter module, and antlr directory in there needs a __init__.py so it is a proper module and can be imported.  The grammar directory is just necessary data files.  I'm hacking together something that will hopefully work for me, but I'd love to see your PR.

**Comment by aaronsven** [comment]
Looks like we already made the change here. Also there is an init.py in the antlr directory
