### ISSUE TITLE
Possible Bugs

### ISSUE THREAD

**Issue by Thinagar-Sivadas** [awslabs/aws-appflow-custom-connector-python#33]
Hello Guys, noticed some issues with certain files as listed below:

File: aws-appflow-custom-connector-python/custom_connector_sdk/auth.py
Issue:
1) **non-default argument follows default argument**
![image](https://user-images.githubusercontent.com/67793749/185560828-b3c3fbdf-8870-4495-992c-71d4afc565a4.png)

File: aws-appflow-custom-connector-python/Dockerfile
Issue:
1)  Shouldn't this be the respective commands? (Bold text is the newly added portion):
COPY custom_connector_example ${LAMBDA_TASK_ROOT}**/custom_connector_example** 
COPY custom_connector_sdk ${LAMBDA_TASK_ROOT}**/custom_connector_sdk** 
COPY custom_connector_queryfilter ${LAMBDA_TASK_ROOT}**/custom_connector_queryfilter**
(if i did not copy over with the folder, i could not run the lambda function as the module could not be found. )

After making the above mentioned changes **(No other code changes)**. I tried registering the connector with the default custom connector based on salesforce implementation.  I got an error while registering the connector (attached below). I have been following the steps as per the readme. 

![image](https://user-images.githubusercontent.com/67793749/185567448-b514f3a5-a6a5-4e46-8961-f7c089854d00.png)

I am relatively new to AWS services. Any help would greatly be appreciated!

**Comment by aaronsven** [comment]
Hi, you can check the lambda logs to see if there is an error

**Comment by sh9694** [comment]
This is fixed
