### ISSUE TITLE
Debugging after deployment

### ISSUE THREAD

**Issue by jorgepulidoibm** [awslabs/aws-appflow-custom-connector-python#34]
Hi there, I am trying to create a custom connector with the SDK as provided but as I can see, the lambda stops receiving requests once the connector is created, so when I try to see what is going on while creating a connection, I cannot see any logs at all.

I have also noticed that if I delete de lambda, the connector still serves the connection creation menu, so I assume that there is some layer where the lambda is cloned and I just do not have permissions to see it/I'm not being able to find it.

If you could provide a bit of information it would be great. We are considering using appflow for a big data migration but we would need to be able to create a custom connector wisely.

Thank you!

**Comment by aaronsven** [comment]
The connector configuration is cached which is why you can still see the connection menu. Logs should be available in the Lambda log group.
